spring:
  application:
    name: BootProj03-LayeredApp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: pavankumar
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##pavan
