spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    oracleucp:
      minPoolSize: 10
      time-to-live-connection-timeout: 100000
    orcaleucp:
      maxPoolSize: 100
    password: pavankumar
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##pavan
