c3P0:
  maxSize: 100
  minSize: 10
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pavankumar
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql:///springpractice
    username: root
