spring:
  application:
    name: BootProj10-LayeredAppFor4Profiles
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    dbcp2:
      initial-size: 10
      max-conn-lifetime-millis: 100000
      max-total: 100
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pavankumar
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///springpractice
    username: root
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pavankumar
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql:///springpractice
    username: root
---
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    oracleucp:
      minPoolSize: 10
      time-to-live-connection-timeout: 100000
    orcaleucp:
      maxPoolSize: 100
    password: pavankumar
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##pavan
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      keepalive-time: 10000
      maximumPoolSize: 100
      minimum-idle: 10
    password: pavankumar
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##pavan
 
 
 
 
 
 
 
 
 
 
  
